@extends('base')

@section('title', 'Corse 2023')

@section('content')
    <h1>Corse 2023</h1>
    <h2>Jour 1 : vendredi 12 mai 2023</h2>
    <p>Cheseaux-sur-Lausanne → Livourne (18:00-01:00). C'est le départ !!! La réserve de bières est au frais et deux énormes sandwish pesto-aubergines-fromage n'attendent qu'a être bouffés lors d’une petite halte en bas du Val d'Aoste. On alterne la conduite, mais c'est Vivi qui se prend l'orage et des trombes d'eau sur l'autoroute ! Wallace semble un peu inquiet. Il se demande peut être ce qui l'attend et ne sait pas encore qu'il s'apprête à vivre son premier grand voyage en bus ! Notre route s'est terminée par une charmante nuitée entre deux camions au port de Livourne. Vue privilégiée sur la raffinerie, poubelles débordante et débris de verre sur le bas côté. Fonctionnel.</p>
    <h2>Jour 2 : samedi 13 mai 2023</h2>
    <p>5 heures de sommeil dans le bruit assourdissant d'un port qui ne dort jamais. On se lève tôt. En sortant du bus, j'entrevois une bouteille remplie de pisse gisant au sol, les yeux encore collés par la nuit courte. Sans doutes a t'elle été déposée là délicatement par un camionneur barbu en marcel taché de mayonnaise... Le grand ferry nous attend déjà. Un peu plus de 4 heures de traversée sont prévus dans ce monstre d'acier, pouvant avaler 650 véhicules et accueillir plus de 1800 passagers. La marine nous va bien et c'est portés par le vent du large que nous avons décapsulés notre première bière Corse (une Pietra) à 09:30 le matin. Ce fut un moment fort agréable, même si les volutes de fumée sombre et poisseuses sortant des énormes échappements du bateau nous confortent dans l'idée que nous ne serons jamais clients pour une croisière. Un merci particulier à Wallace, qui s'est fait un plaisir de faire son pipi à 50 centimètres du bac de galets prévu à cet effet. Une fois débarqués à Bastia et après avoir achetés quelques provisions (au moment au j'écris ces lignes, je ne sais toujours pas si c'est l'odeur du formage Corse ou de mes pieds qui embaume notre bus), nous nous sommes rendu à notre premier emplacement sauvage, au milieu de nul part entre Bastia et Corte (42.441239, 9.174225). Fatigués par notre nuit courte, nous sommes restés tranquillement dans ce havre de calme et de paix durant l'après midi et pour la nuit, entourés de vaches et d'oiseaux.<br><br>Menu du soir : pâtes au pesto rouge, copeaux de parmesan, duo d'olives vertes et noires et tapenade ail piment.</p>
    <h2>Jour 3 : dimanche 14 mai 2023</h2>
    <p>Corse, nous voici ! Au programme, trajet jusqu'à la bergerie de Grottelle (vallée de la Restonica) via Corte en passant par les petites routes escarpées D18 et D623, puis randonnée depuis la bergerie jusqu'au lac Melu. C'est la première sortie en montagne pour Wallace ! Malheureusement, nous n'avons pas pu atteindre le lac au sommet à cause de chaînes et d'échelles un peu trop compliqué à franchir avec un chien. Tant pis, ce lieu est incroyable, typique de chez typique. On y mange sur place après notre superbe marche avortée, qui a duré un peu plus de 2 heures : Bière Corse, pain Corse, fromage Corse, jambon Corse, bergers Corse moustachus renfrognés mais hyper accueillant à l'accent acéré. Le bonheur. Pour la suite de la journée, nous continuons notre traversée est-ouest par la D84, qui doit nous amener jusqu'à Porto.  Nous trouvons notre emplacement sauvage du jour en pleine forêt (42.287979, 8.93105), entourés cette fois-ci de plusieurs dizaines de cochons en libertés.<br><br>Menu du soir : Fromage Corse, pain et confiture de figues, salade de tomates et tzatziki.</p>
    <h2>Jour 4 : lundi 15 mai 2023</h2>
    <p>Café serré sous les premiers rayons de soleil traversant les pins, musique Corse à fond, départ en direction de Porto. On passe le col de Vergio en bavant devant la beauté majestueuse des hautes cimes et entamons la descente spectaculaire nous menant au golfe. En bas, la grande bleue tutoie le rouge de la roche plutonique des calanches. Voyager hors saison nous permet de profiter pleinement de cet endroit habituellement prisé par les touristes. Nous décidons de passer une nuit en camping (municipal, 18,50€), cela nous permettra de visiter le coin plus facilement et de se nettoyer pour de vrai ! Le trajet à pied de notre emplacement jusqu'à la petite plage traverse une forêt d'immenses eucalyptus centenaires, plantés jadis pour assénir un marais qui était propice à la prolifération de la malaria. Galvanisée par la beauté puissante du bord de mer, Vivi se baigne dans une eau à moins de 15 degrés !<br><br>Menu du soir : nous nous sommes fait arnaquer au restaurant "Le Romantique". 36,50 € pour une tentacule de poulpe, un calamar et deux crevettes noyés dans de la purée de patate ! 3 morceaux de pain pour 2 et même pas assez d'aioli. Non mais sérieux, on a terminé notre assiette à la moitié de notre premier verre de vin (Corse, qui lui était excellent)... Décevant.<br><br>Pour se consoler, on ne s'est pas privé d'une bière sous les étoiles, avec en prime le passage d'un train de 16 satellites Starlink.</p>
    <h2>Jour 5 : mardi 16 mai 2023</h2>
    <p>Nous repartons de Porto par la D81 avec comme objectif de rouler le long des côtes jusqu'à Ajaccio, puis de tracer à nouveau dans la montagne. Le long du golfe, entre Porto et Piana, nous nous baladons durant une heure entre les lieux-dits de la tête de chien et du château fort. Il s'agit de deux formations rocheuses reliés par un parcours avec vue imprenable sur la mer. Le parcours du littoral entre Piana et Ajaccio est un peu moins intéressant. Nous avons tout de même effectué un petit arrêt à la plage du Capo di Feno. Plusieurs surfeurs profitaient de la houle pour dompter les vagues, qui n'avaient rien à envier à celles de l'atlantique ! (Pas de baignade cette fois ci). Aujourd'hui, l'accès à notre cible de camping sauvage s'est soldé par un échec. L'entrée du petit parking était bloquée par un chantier. Le demi tour n'est pas envisageable à cause des travaux, je suis obligé d'effectuer une manœuvre "à la Corse". (comprendre : utiliser une route à sens unique en sens inverse pour rejoindre la route principale). Pas de grands dangers pour ce petit écart de conduite, si ce n'est que le premier véhicule que nous avons croisés une fois le droit chemin retrouvé était une bagnole... de flics ! Nous avons pour finir trouvé un emplacement au sommet du col St Eustache.<br><br>Menu du soir : Apéro Corse (Pietra Pale Ale, olives et Canisrelli aux herbes du maquis), Polenta à la Scarmozza.</p>
    <h2>Jour 6 : mercredi 17 mai 2023</h2>
    <p>Il est fréquent de voir un panneau de signalisation tagé ou criblé de balles. Le Corse semble souvent caractériel, parfois anarchique et profondément attaché à la liberté et l'indépendance de son pays. Les vans ne sont pas toujours les bienvenus, on nous regarde parfois de travers. Les automobilistes du coin ont le klaxon facile, de préférence au petit matin. On s'en fout, on est justement pas des lève tard ! Notre trajet nous fait passer par plusieurs petits villages de montagne (Aullène, Quenza, Zonza), jusqu'au col de Bavel. Un gars, accompagné de sa femme et de son petit, nous interpelle en anglais : "I like your van !  It's my dream to have one. Where are you from ?" On discute 5 minutes, ce sont des hollandais fan du Valais ! Ils y vont presque chaque année. "We came 3 times to the Camping des Glaciers in La Fouly. We will be there this summer". On sympathise, je lui file mon numéro. Nous avons prévus de nous revoir la bas en juillet. Plusieurs itinéraire de randonnée s'offrent à nous, on choisi une boucle au hasard. S'en suit une magnifique marche en forêt, sans trop de difficultés. Le temps se détériore, le col est maintenant sous le brouillard. Nous rebroussons chemin pour retrouver le soleil au petit camping familial I Suvari (21,50€), situé en pleine campagne au milieu des moutons et des chênes liège (Il faut 9 ans pour que le liège se régénère après son prélèvement).<br><br>Menu du soir : salade de poulpe, pain, formage Corse, houmous, olives, chips, beurre de homard.</p>
    <h2>Jour 7 : jeudi 18 mai 2023</h2>
    <p>Lors de notre voyage, nous avons croisés pleins de petites bêtes en liberté sur le bord de route. Vaches, moutons, chèvres, mouflons (un seul, l'air outré) et cochons. En fait, peu sont réellement sauvages (ils sont souvent marqués), mais ils semblent se déplacer plutôt librement. Presque chaque nuits, nous avons entendu le hibou petit-duc et ses petits sifflements monocorde. Pour éviter la pluie, nous planifions de retourner sur la côte Est en franchissant une deuxième fois les cols St Eustache et Bavel. S'en suit une remontée tranquille nous rapprochant de Bastia. Nous passons la nuit en mode "sauvage", sur un site très proche de la plage.<br><br>Menu du soir : pâtes aux sardines/thon vegan, pesto, huile piquante.</p>
    <h2>Jour 8 : vendredi 19 mai 2023</h2>
    <p>08:15 : "Nico, ça me semblait bizarre que les zurichois à côté du nous soient parti autant tôt ce matin. Je viens de vérifier, notre bateau de retour partait aujourd'hui à 08:00". Non mais quel bobet... Je fais les réservations, sauvegarde les documents en local sur mon téléphone, garde à l'esprit que le billet d'embarquement pour le retour doit être généré quelques jours avant notre départ et pourtant, pourtant, je me cale dans le ciboulot que nous repartons le samedi. Évidemment, pas de remboursement possible. On achète un nouveau billet à 160€. Le prix de deux restos quoi. Le sale temps nous a rattrapé, il pleut par intermittence. Nous passons la journée à lire et se promener sur la plage. Wallace apprend le jeu du bâton (on lance, il ramène...), il ne peut plus s'arrêter, un bon moyen pour le crever ! Ce petit fou aura perdu 3 dents de lait durant la semaine, que nous avons toutes pu récupérer.<br><br>Menu du soir : Salade de la mer au restaurant Via Luna by Pinarellu (juste à côté de notre emplacement sauvage).</p>
    <h2>Jour 9 : samedi 20 mai 2023</h2>
    <p>C'est la bonne. On se lève tôt pour effectuer la demi heure de route qui nous sépare de Bastia. Embarquement easy, beaucoup moins de monde que pour l'aller. Une fois à bord, Wallace est stressé. Pour se décontracter, il fait caca mou sur la moquette. Deux fois. Ce cochon a vidé son stock de sac à merde en 5 minutes, belle performance ! De retour sur la terre ferme, on vise le resto de Postillon dans notre petit village de Cheseaux comme point d'arrivée. Nous avons passé tout notre trajet du retour à écouter le podcast "Face Nord" de la RTS.<br><br>Menu du soir : Penne à la Ciccio et Pizza Fouette Cocher.</p>
@endsection